from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
    initial=True
    dependencies=[]
    operations=[
      migrations.CreateModel(name='Candidate',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('registration_id',models.CharField(editable=False,max_length=30,unique=True)),('full_name',models.CharField(max_length=150)),('phone',models.CharField(max_length=30)),('email',models.EmailField(blank=True,max_length=254)),('current_location',models.CharField(max_length=150)),('highest_qualification',models.CharField(max_length=150)),('experience',models.CharField(max_length=100)),('key_skills',models.TextField()),('preferred_role',models.CharField(max_length=150)),('preferred_work_location',models.CharField(blank=True,max_length=150)),('expected_salary',models.CharField(blank=True,max_length=100)),('status',models.CharField(choices=[('NEW','NEW'),('RESUME_REVIEWED','RESUME REVIEWED'),('CONTACTED','CONTACTED'),('INTERVIEW','INTERVIEW'),('REFERRED','REFERRED'),('SELECTED','SELECTED'),('JOINED','JOINED')],default='NEW',max_length=30)),('consent',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True))],options={'ordering':['-created_at']}),
      migrations.CreateModel(name='Resume',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('file',models.FileField(upload_to='resumes/%Y/%m/')),('original_name',models.CharField(max_length=255)),('uploaded_at',models.DateTimeField(auto_now_add=True)),('candidate',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='resume',to='candidates.candidate'))]),
      migrations.CreateModel(name='Interview',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('scheduled_at',models.DateTimeField(blank=True,null=True)),('employer',models.CharField(blank=True,max_length=200)),('notes',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('candidate',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='interviews',to='candidates.candidate'))]),
      migrations.CreateModel(name='Referral',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('employer',models.CharField(max_length=200)),('role',models.CharField(blank=True,max_length=200)),('notes',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('candidate',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='referrals',to='candidates.candidate'))]),
      migrations.CreateModel(name='Placement',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('employer',models.CharField(max_length=200)),('role',models.CharField(blank=True,max_length=200)),('joined_on',models.DateField(blank=True,null=True)),('notes',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('candidate',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='placement',to='candidates.candidate'))]),
    ]
